export type PermissionRowType = {
  id: number
  name: string
  createdDate: string
  assignedTo: string[]
}

export enum PermissionEnum {
  MARKETING_RECORD_UPDATE_PERMISSION = 'MARKETING_RECORD_UPDATE_PERMISSION',
  PORTFOLIO_RECORD_UPDATE_PERMISSION = 'PORTFOLIO_RECORD_UPDATE_PERMISSION',
  PROJECT_ATTRIBUTE_RECORD_UPDATE_PERMISSION = 'PROJECT_ATTRIBUTE_RECORD_UPDATE_PERMISSION'
}
